'npx hardhat compile --force' running
Compiling 17 files with 0.8.1
Compilation finished successfully

Warning: Contract code size exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
  --> contracts/Pair.sol:18:1:
   |
18 | contract Pair is IPair {
   | ^ (Relevant source part starts here and spans across multiple lines).


Warning: Contract code size exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
  --> contracts/Factory.sol:10:1:
   |
10 | contract Factory is IFactory {
   | ^ (Relevant source part starts here and spans across multiple lines).



Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/slither/__main__.py", line 723, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Library/Python/3.8/site-packages/slither/__main__.py", line 71, in process_all
    compilations = compile_all(target, **vars(args))
  File "/Library/Python/3.8/site-packages/crytic_compile/crytic_compile.py", line 489, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/Library/Python/3.8/site-packages/crytic_compile/crytic_compile.py", line 109, in __init__
    self._compile(**kwargs)
  File "/Library/Python/3.8/site-packages/crytic_compile/crytic_compile.py", line 417, in _compile
    self._platform.compile(self, **kwargs)
  File "/Library/Python/3.8/site-packages/crytic_compile/platform/hardhat.py", line 118, in compile
    contract_filename = convert_filename(
  File "/Library/Python/3.8/site-packages/crytic_compile/utils/naming.py", line 102, in convert_filename
    raise InvalidCompilation(f"Unknown file: {filename}")
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: contracts/libraries/SafeERC20.sol
ERROR:root:None
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/slither/__main__.py", line 723, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Library/Python/3.8/site-packages/slither/__main__.py", line 71, in process_all
    compilations = compile_all(target, **vars(args))
  File "/Library/Python/3.8/site-packages/crytic_compile/crytic_compile.py", line 489, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/Library/Python/3.8/site-packages/crytic_compile/crytic_compile.py", line 109, in __init__
    self._compile(**kwargs)
  File "/Library/Python/3.8/site-packages/crytic_compile/crytic_compile.py", line 417, in _compile
    self._platform.compile(self, **kwargs)
  File "/Library/Python/3.8/site-packages/crytic_compile/platform/hardhat.py", line 118, in compile
    contract_filename = convert_filename(
  File "/Library/Python/3.8/site-packages/crytic_compile/utils/naming.py", line 102, in convert_filename
    raise InvalidCompilation(f"Unknown file: {filename}")
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: contracts/libraries/SafeERC20.sol

